"""Constants used across the SCTVA pipeline."""

SUPPORTED_LANGUAGES = {
    "python", "java", "c", "cpp", "c++", "h", "hpp",
    "markdown", "makefile", "text", "json", "yaml", "xml", "plain", "raw", "other",
}

ACTION_RENAME_SYMBOL = "rename_symbol"
ACTION_RENAME_METHOD = "rename_method"
ACTION_EXTRACT_CONSTANT = "extract_constant"
ACTION_INTRODUCE_CONSTANT = "introduce_constant"
ACTION_REPLACE_LITERAL = "replace_literal"
ACTION_INJECT_SYNTAX_ERROR = "inject_syntax_error"
ACTION_FAULT_INJECTION = "fault_injection"
ACTION_NOOP = "noop"
ACTION_REMOVE_DEAD_CODE = "remove_dead_code"
ACTION_NARROW_EXCEPTION_HANDLER = "narrow_exception_handler"
ACTION_EXTRACT_METHOD = "extract_method"
ACTION_EXTRACT_CLASS = "extract_class"
ACTION_EXTRACT_PYTHON_CLASS = "extract_python_class"
ACTION_EXTRACT_JAVA_CLASS = "extract_java_class"
ACTION_EXTRACT_C_COMPONENT = "extract_c_component"
ACTION_REPLACE_UNSAFE_FUNCTION = "replace_unsafe_function"
ACTION_ENCAPSULATE_VARIABLE = "encapsulate_variable"
ACTION_ENCAPSULATE_C_VARIABLE = "encapsulate_c_variable"
ACTION_MOVE_C_FUNCTION = "move_c_function"
ACTION_NORMALIZE_MULTILINE_STATEMENT = "normalize_multiline_statement"
ACTION_INTRODUCE_PARAMETER_OBJECT = "introduce_parameter_object"
ACTION_INTRODUCE_JAVA_PARAMETER_OBJECT = "introduce_java_parameter_object"
ACTION_INTRODUCE_PYTHON_PARAMETER_OBJECT = "introduce_python_parameter_object"
ACTION_INTRODUCE_C_PARAMETER_OBJECT = "introduce_c_parameter_object"
ACTION_MOVE_PYTHON_METHOD = "move_python_method"
ACTION_INLINE_PYTHON_CLASS = "inline_python_class"
ACTION_HIDE_DELEGATE = "hide_delegate"
ACTION_REPLACE_CONDITIONAL_WITH_POLYMORPHISM = "replace_conditional_with_polymorphism"
ACTION_REPLACE_NESTED_CONDITIONAL_WITH_GUARD_CLAUSES = "replace_nested_conditional_with_guard_clauses"
ACTION_REPLACE_CONDITIONAL_WITH_GUARD_CLAUSES = "replace_conditional_with_guard_clauses"
ACTION_SIMPLIFY_CONDITIONAL_LOOP = "simplify_conditional_loop"
ACTION_GUARD_CLAUSES = "guard_clauses"

SUPPORTED_ACTIONS = {
    ACTION_RENAME_SYMBOL,
    ACTION_RENAME_METHOD,
    ACTION_EXTRACT_CONSTANT,
    ACTION_INTRODUCE_CONSTANT,
    ACTION_REPLACE_LITERAL,
    ACTION_INJECT_SYNTAX_ERROR,
    ACTION_FAULT_INJECTION,
    ACTION_NOOP,
    ACTION_REMOVE_DEAD_CODE,
    ACTION_NARROW_EXCEPTION_HANDLER,
    ACTION_EXTRACT_METHOD,
    ACTION_EXTRACT_CLASS,
    ACTION_EXTRACT_PYTHON_CLASS,
    ACTION_EXTRACT_JAVA_CLASS,
    ACTION_EXTRACT_C_COMPONENT,
    ACTION_REPLACE_UNSAFE_FUNCTION,
    ACTION_ENCAPSULATE_VARIABLE,
    ACTION_ENCAPSULATE_C_VARIABLE,
    ACTION_MOVE_C_FUNCTION,
    ACTION_NORMALIZE_MULTILINE_STATEMENT,
    ACTION_INTRODUCE_PARAMETER_OBJECT,
    ACTION_INTRODUCE_JAVA_PARAMETER_OBJECT,
    ACTION_INTRODUCE_PYTHON_PARAMETER_OBJECT,
    ACTION_INTRODUCE_C_PARAMETER_OBJECT,
    ACTION_MOVE_PYTHON_METHOD,
    ACTION_INLINE_PYTHON_CLASS,
    ACTION_HIDE_DELEGATE,
    ACTION_REPLACE_CONDITIONAL_WITH_POLYMORPHISM,
    ACTION_REPLACE_NESTED_CONDITIONAL_WITH_GUARD_CLAUSES,
    ACTION_REPLACE_CONDITIONAL_WITH_GUARD_CLAUSES,
    ACTION_SIMPLIFY_CONDITIONAL_LOOP,
    ACTION_GUARD_CLAUSES,
}

PARAMETER_OBJECT_ACTIONS = frozenset({
    ACTION_INTRODUCE_PARAMETER_OBJECT,
    ACTION_INTRODUCE_JAVA_PARAMETER_OBJECT,
    ACTION_INTRODUCE_PYTHON_PARAMETER_OBJECT,
    ACTION_INTRODUCE_C_PARAMETER_OBJECT,
})

PARAMETER_OBJECT_ACTION_BY_LANGUAGE = {
    "java": ACTION_INTRODUCE_JAVA_PARAMETER_OBJECT,
    "python": ACTION_INTRODUCE_PYTHON_PARAMETER_OBJECT,
    "c": ACTION_INTRODUCE_C_PARAMETER_OBJECT,
}

# ``extract_class`` is retained only for legacy RDP plans. Once SCTVA resolves
# the target file, it specializes the action to one language-specific operation.
EXTRACT_CLASS_ACTIONS = frozenset({
    ACTION_EXTRACT_CLASS,
    ACTION_EXTRACT_PYTHON_CLASS,
    ACTION_EXTRACT_JAVA_CLASS,
    ACTION_EXTRACT_C_COMPONENT,
})

EXTRACT_CLASS_ACTION_BY_LANGUAGE = {
    "python": ACTION_EXTRACT_PYTHON_CLASS,
    "java": ACTION_EXTRACT_JAVA_CLASS,
    "c": ACTION_EXTRACT_C_COMPONENT,
}

DEFAULT_STRUCTURAL_THRESHOLD_PYTHON = 0.55
DEFAULT_STRUCTURAL_THRESHOLD_JAVA = 0.50
DEFAULT_STRUCTURAL_THRESHOLD_C = 0.52

DEFAULT_CONFIDENCE_WEIGHTS = {
    "syntax": 0.35,
    "structural": 0.35,
    "behavioral": 0.30,
}

DEFAULT_INVARIANT_WEIGHT = 0.15

KNOWN_UNSAFE_JAVA_ACTIONS = {ACTION_INJECT_SYNTAX_ERROR}
KNOWN_UNSAFE_C_ACTIONS = {ACTION_INJECT_SYNTAX_ERROR}

DEFAULT_TIMEOUT_SECONDS = 10
