"""Constants used across the SCTVA pipeline."""

SUPPORTED_LANGUAGES = {"python", "java"}

ACTION_RENAME_SYMBOL = "rename_symbol"
ACTION_EXTRACT_CONSTANT = "extract_constant"
ACTION_REPLACE_LITERAL = "replace_literal"
ACTION_INJECT_SYNTAX_ERROR = "inject_syntax_error"
ACTION_FAULT_INJECTION = "fault_injection"
ACTION_NOOP = "noop"

SUPPORTED_ACTIONS = {
    ACTION_RENAME_SYMBOL,
    ACTION_EXTRACT_CONSTANT,
    ACTION_REPLACE_LITERAL,
    ACTION_INJECT_SYNTAX_ERROR,
    ACTION_FAULT_INJECTION,
    ACTION_NOOP,
}

DEFAULT_STRUCTURAL_THRESHOLD_PYTHON = 0.55
DEFAULT_STRUCTURAL_THRESHOLD_JAVA = 0.50

DEFAULT_CONFIDENCE_WEIGHTS = {
    "syntax": 0.35,
    "structural": 0.35,
    "behavioral": 0.30,
}

DEFAULT_INVARIANT_WEIGHT = 0.15

KNOWN_UNSAFE_JAVA_ACTIONS = {ACTION_INJECT_SYNTAX_ERROR}

DEFAULT_TIMEOUT_SECONDS = 10
