/**
 * impactSummary.test.mjs
 * ======================
 * R26-SE-008 | Bandara S M Y M | IT22277886
 *
 * summariseSelection() is a deliberate duplicate of
 * backend/domain/impact_model.py::aggregate — the panel has to update on the
 * same frame as the checkbox, which a round trip cannot do.
 *
 * Duplicated logic drifts. So the fixture next to this file is generated BY
 * the Python original: real impact records plus the aggregate Python produced
 * for five different selections. This test replays those selections through
 * the JavaScript mirror and asserts an exact match, field by field.
 *
 * If the two ever disagree, the developer is shown one projection live and a
 * different one is written to the audit trail. That is the failure this exists
 * to catch.
 *
 * Regenerate the fixture after changing the Python model.
 * Dependency-free:
 *
 *     npm run test:impact         (from frontend/)
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { summariseSelection } from "./impactSummary.js";

const here = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(join(here, "impactSummary.fixture.json"), "utf-8"));

let failures = 0;
const check = (label, condition, detail = "") => {
  if (!condition) failures += 1;
  console.log(`  [${condition ? "PASS" : "FAIL"}] ${label}${!condition && detail ? `  -- ${detail}` : ""}`);
};

// Fields the JS mirror is responsible for. `error_band` is a backend constant
// the panel reads straight off the record, so it is not recomputed here.
const NUMERIC_FIELDS = [
  "selected_count", "executable_count", "advisory_count", "skipped_count",
  "quality_before", "quality_projected", "quality_ceiling",
  "captured_points", "ceiling_points", "capture_rate",
  "forgone_points", "quarterly_interest", "effort_minutes",
  "max_risk", "mean_risk",
];

console.log("\nJavaScript mirror vs. the Python model it duplicates");
console.log(`  fixture: ${fixture.records.length} records, baseline ${fixture.quality_before}\n`);

for (const [key, expected] of Object.entries(fixture.expected)) {
  const ids = key === "" ? [] : key.split(",");
  const actual = summariseSelection(fixture.records, new Set(ids), fixture.quality_before);
  const label = ids.length ? ids.join(", ") : "(nothing selected)";

  const wrong = NUMERIC_FIELDS.filter((f) => actual[f] !== expected[f]);
  check(
    `selection [${label}] — all ${NUMERIC_FIELDS.length} figures match`,
    wrong.length === 0,
    wrong.map((f) => `${f}: js=${actual[f]} py=${expected[f]}`).join("; ")
  );

  const actualWarnings = actual.warnings.map((w) => w.level).sort();
  const expectedWarnings = expected.warnings.map((w) => w.level).sort();
  check(
    `selection [${label}] — same warnings raised`,
    JSON.stringify(actualWarnings) === JSON.stringify(expectedWarnings),
    `js=${JSON.stringify(actualWarnings)} py=${JSON.stringify(expectedWarnings)}`
  );

  const actualText = actual.warnings.map((w) => w.message).sort();
  const expectedText = expected.warnings.map((w) => w.message).sort();
  check(
    `selection [${label}] — same warning wording`,
    JSON.stringify(actualText) === JSON.stringify(expectedText),
    `js=${JSON.stringify(actualText)}\n           py=${JSON.stringify(expectedText)}`
  );
}

console.log("\nedge cases");
const empty = summariseSelection([], new Set(), 0);
check("no records at all does not throw", empty.selected_count === 0);
check("and reports a zero capture rate rather than NaN", empty.capture_rate === 0);

const missing = summariseSelection(fixture.records, new Set(["not-a-real-id"]), 70);
check("an unknown id selects nothing", missing.selected_count === 0);

console.log(`\n${failures ? `FAILED: ${failures} check(s)` : "JS AND PYTHON AGREE ON EVERY CASE"}`);
process.exit(failures ? 1 : 0);
