/**
 * DIWOAgentPage.jsx
 * =================
 * R26-SE-008 | Bandara S M Y M | IT22277886
 *
 * FIXES APPLIED (frontend):
 *  [F1] All workflow state (workflowId, planData, transformationData, metrics)
 *       is sourced from API responses — not from diwoData.js static mocks.
 *       diwoData.js is only used for the initial smell list (CUQA_DATA) until
 *       a real file-upload endpoint is added.
 *  [F2] backendBusy flag prevents double-submits on slow connections.
 *  [F3] Errors are surfaced in the audit log (type:"danger") instead of
 *       silently falling through to mock data.
 *  [F4] handleTransformComplete receives and stores real backend data.
 *  [F5] handleRollback awaits the backend call before changing phase.
 *  [F6] Phase guard: user cannot advance past phase 0 until workflowId exists.
 *  [F7] DIWOAgentService path corrected to relative import for portability.
 */

import { useEffect, useState } from "react";
import AuditSidebar from "./AuditSidebar";
import CodeSmellApprovalPage from "./CodeSmellApprovalPage";
import RefactoringPlanApprovalPage from "./RefactoringPlanApprovalPage";
import ResultsApprovalPage from "./ResultsApprovalPage";
import TransformationApprovalPage from "./TransformationApprovalPage";
import ComparisonView from "./ComparisonView.jsx";
import { C, StepBar } from "./diwoTheme.jsx";
import { CUQA_DATA } from "./data/diwoData.js";
// Pure helper only — the plan itself is generated by the DIWO backend, which
// owns the single POST to the RDP agent's /generate.
import { enrichPlanWithTrace } from "./rdpApi";

// ─── API service ─────────────────────────────────────────────────────────────
// FIX [F7]: Inline the service here so the path is always correct regardless
// of where this component is mounted in the project.
const BASE = import.meta?.env?.VITE_API_URL || "http://localhost:5001/api";

const api = {
  async post(path, body) {
    const res = await fetch(`${BASE}${path}`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    const json = await res.json();
    if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
    return json;
  },
  async get(path) {
    const res = await fetch(`${BASE}${path}`);
    const json = await res.json();
    if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
    return json;
  },
};

// ─── Phase metadata ───────────────────────────────────────────────────────────
const PHASE_TITLES = [
  "Code Smell Review",
  "Refactoring Plan Review",
  "Safe Code Transformation",
  "Refactoring Results",
  "Comparison",
];

const PHASE_DESCRIPTIONS = [
  "Analyze detected code smells from Code Understanding Agent and select smells to forward to the Refactoring Planning Agent.",
  "Review, approve, reject, or reprioritize the refactoring plan generated by the Refactoring Planning Agent.",
  "Safe Code Transformation & Validation Agent is applying approved refactoring actions with full behavioral validation.",
  "Review the refactored output, validation report, and confidence metrics. Accept, rollback, or start a new session.",
  "Compare before/after quality metrics and review the audit trail after transformation.",
];

// ─── Smell builder ────────────────────────────────────────────────────────────
/**
 * Converts CUQA_DATA.files into the smell format the backend expects.
 *
 * This is the OFFLINE fallback only. The normal path is
 * POST /workflows/from-cuqa, where the backend pulls the live quality report
 * from the CUQA agent (POST http://localhost:8080/api/quality-report) and seeds
 * the workflow from it — see bootstrapWorkflow() below.
 */
function buildBackendSmells() {
  const smells = [];
  CUQA_DATA.files.forEach((file) => {
    (file.code_smells || []).forEach((smell, idx) => {
      smells.push({
        id: `${file.relative_path}:${smell.line}:${idx}`,
        type: smell.type,
        severity: smell.severity,
        location: {
          file: file.relative_path,
          class: file.file?.replace(/\.[^.]+$/, "") || "UnknownClass",
          method: null,
          lines: [smell.line || 0, smell.line || 0],
        },
        metrics: {
          lines_of_code: file.metrics?.lines_of_code || 0,
          quality_score: file.quality_score || 0,
        },
        message: smell.message || "",
      });
    });
  });
  return smells;
}

// ─── Component ────────────────────────────────────────────────────────────────
export default function DIWOAgentPage() {
  const [phase, setPhase]         = useState(0);
  const [workflowId, setWorkflowId]           = useState(null);
  const [workflowLanguage, setWorkflowLanguage] = useState("java");
  const [cuqaReport, setCuqaReport]           = useState(null);   // live Agent 1 report
  const [planData, setPlanData]               = useState(null);
  // Which agent produced planData, where, and why — straight from the
  // /select-smells response. Stage 2 renders this instead of re-planning.
  const [planMeta, setPlanMeta]               = useState(null);
  // Only the steps the developer approved — this is what Stage 3 sends to SCTVA.
  const [approvedPlan, setApprovedPlan]       = useState(null);
  const [transformationData, setTransformationData] = useState(null);
  const [metricsBeforeApi, setMetricsBeforeApi]     = useState(null);
  const [metricsAfterApi, setMetricsAfterApi]       = useState(null);
  const [backendBusy, setBackendBusy]         = useState(false);  // FIX [F2]
  const [workflow, setWorkflow]               = useState(null);
  const [auditLog, setAuditLog]               = useState([
    { id: `local-init`, time: new Date().toLocaleTimeString(), event: "Session initialized", type: "info" },
  ]);

  const addLog = (event, type = "info") =>
    setAuditLog((prev) => [
      ...prev,
      { id: `local-${Date.now()}-${Math.random()}`, time: new Date().toLocaleTimeString(), event, type },
    ]);

  // ── On mount: create backend workflow ─────────────────────────────────────
  /**
   * Preferred path: POST /workflows/from-cuqa — the DIWO backend calls the CUQA
   * agent's POST /api/quality-report, normalizes it, and seeds the workflow with
   * the real detected smells. The same report is handed to Stage 1 so the file
   * paths the developer selects always resolve against the workflow's smells.
   *
   * Fallback: the bundled sample report via POST /workflows, so the flow stays
   * usable when the CUQA agent is not running or has no repository loaded.
   */
  useEffect(() => {
    (async () => {
      setBackendBusy(true);
      try {
        try {
          const res = await api.post("/workflows/from-cuqa", {});
          setWorkflowId(res.workflow_id);
          setWorkflowLanguage(res.language || "java");
          setMetricsBeforeApi(res.metrics_before || null);
          setCuqaReport(res.report || null);
          addLog(
            `CUQA report ingested from ${res.cuqa_url || "CUQA agent"}: ` +
            `${res.report?.summary?.files_analyzed ?? 0} file(s), ${res.smell_count ?? 0} smell(s)`,
            "success"
          );
          addLog(`Backend workflow created: ${res.workflow_id} (target: ${res.target})`, "success");
          return;
        } catch (e) {
          // FIX [F3]: Surface the reason; do not silently fall to mock.
          addLog(`Live CUQA ingestion unavailable: ${e.message}`, "warn");
        }

        const smells = buildBackendSmells();
        const res = await api.post("/workflows", {
          target: "ECommerceSystem.java",
          language: "java",
          smells,
        });
        setWorkflowId(res.workflow_id);
        setWorkflowLanguage("java");
        setMetricsBeforeApi(res.metrics_before || null);
        addLog(`Backend workflow created from sample report: ${res.workflow_id}`, "warn");
      } catch (e) {
        addLog(`Backend unavailable: ${e.message}. Running in offline mode.`, "danger");
      } finally {
        setBackendBusy(false);
      }
    })();
  }, []);

  /**
   * Stage 1 fetched (or re-analyzed) the CUQA report on its own — either
   * because /workflows/from-cuqa failed on mount, or because the developer
   * pressed "Re-analyze". Log it; the page keeps ownership of that copy so a
   * re-analyze is not overwritten by the report the parent already holds.
   */
  const handleCuqaReportLoaded = (result) => {
    const summary = result?.report?.summary || {};
    addLog(
      `CUQA report loaded (${result?.via === "cuqa-direct" ? "direct" : "via backend"}): ` +
      `${summary.files_analyzed ?? 0} file(s), ${summary.total_code_smells ?? 0} smell(s)`,
      "info"
    );
  };

  /**
   * Store the plan the backend produced from the developer's smell selection.
   *
   * POST /workflows/<id>/select-smells forwards the updated report — selected
   * smells only, files left empty dropped — to the RDP agent and returns the
   * plan plus its decision trace. The trace carries impact / risk / MCDA
   * scores that do not live on the steps, so it is folded in here with the
   * pure enrichPlanWithTrace helper. No second /generate request is made.
   */
  const applyPlanResponse = (res) => {
    const plan = res?.plan || null;
    const trace = res?.trace || null;
    const enriched = plan && trace ? enrichPlanWithTrace(plan, trace) : plan;

    setPlanData(enriched);
    setPlanMeta({
      plan_source:  res?.plan_source || null,
      plan_warning: res?.plan_warning || null,
      rdp_url:      res?.rdp_url || null,
      files_sent:   res?.updated_report?.files?.filter((f) => (f.code_smells || []).length > 0).length ?? null,
      smells_sent:  res?.selected_count ?? null,
      trace,
    });

    if (res?.plan_source === "rdp_agent") {
      addLog(
        `Plan ${plan?.plan_id} generated by the RDP agent (${res.rdp_url}): ` +
        `${plan?.summary?.total_steps ?? 0} step(s) from ${res.selected_count ?? 0} selected smell(s)`,
        "success"
      );
    } else if (plan) {
      addLog(
        `RDP agent unavailable (${res?.plan_warning || "unknown reason"}) — ` +
        `showing the DIWO backend's fallback plan with ${plan?.summary?.total_steps ?? 0} step(s).`,
        "warn"
      );
    }

    return enriched;
  };

  // ── Stage 0 → 1: Smell selection ─────────────────────────────────────────
  const handleSmellsSelected = async (selection) => {
    if (selection && selection.updated_report) {
      // The report-only endpoint does not mutate workflow stage.
      // Persist the same selection through /select-smells so stage becomes plan_approval.
      if (!workflowId) {
        addLog("No backend session — cannot persist smell selection.", "danger");
        return;
      }
      if (backendBusy) return;

      try {
        setBackendBusy(true);
        const report = selection.updated_report;
        const selectedIds = report?.summary?.selected_smell_ids || [];
        // The updated report keeps every analysed file so the developer can see
        // what was excluded — files whose smells were all deselected come back
        // with an empty code_smells list. Forwarding those paths would let the
        // backend re-resolve the selection to every smell in them, undoing the
        // deselection, so only files that still carry smells are sent.
        const filesWithSmells = (report?.files || []).filter(
          (f) => (f.code_smells || []).length > 0
        );
        const selectedFiles = filesWithSmells.map((f) => f.relative_path).filter(Boolean);
        const selectedSmells = filesWithSmells.flatMap((f) =>
          (f.code_smells || []).map((smell) => ({
            file: f.relative_path,
            type: smell.type,
            line: smell.line,
            severity: smell.severity,
            message: smell.message,
          }))
        );

        // Smell-wise selection is per smell, so the file paths are deliberately
        // left out: the backend expands a file path to every smell inside it,
        // which would undo the smells the developer just deselected.
        const selectionMode = selection.selection_mode === "smell" ? "smell" : "file";

        const res = await api.post(`/workflows/${workflowId}/select-smells`, {
          selected_ids: selectedIds,
          ...(selectionMode === "smell" ? {} : { selected_files: selectedFiles }),
          selected_smells: selectedSmells,
          selection_mode: selectionMode,
          feedback: { reason: `Selected in DIWO frontend (${selectionMode}-wise)` },
        });

        addLog(
          `${report.summary?.selected_count ?? 0} smell(s) across ${selectedFiles.length} file(s) approved ` +
          `(${selectionMode}-wise selection); selection persisted.`,
          "success"
        );
        applyPlanResponse(res);
        setWorkflow((prev) => ({
          ...(prev || {}),
          updated_report: res.updated_report || report,
          planning_input: res.planning_input || selection.planning_input || null,
          smell_selection_summary: {
            total_smells: (res.updated_report?.summary?.total_code_smells) || (report?.summary?.total_code_smells) || 0,
            selected_count: res.selected_count || (report?.summary?.selected_count) || 0,
            excluded_count: res.excluded_count || 0,
          },
        }));
        setPhase(1);
      } catch (e) {
        addLog(`Smell selection failed: ${e.message}`, "danger");
      } finally {
        setBackendBusy(false);
      }
      return;
    }

    addLog(`${selection.size} file(s) forwarded to Refactoring Planning Agent`, "success");

    // FIX [F6]: Block if no backend session
    if (!workflowId) {
      addLog("No backend session — cannot forward smells. Check backend connection.", "danger");
      return;
    }

    // FIX [F2]: Block double-submit
    if (backendBusy) return;

    try {
      setBackendBusy(true);
      const allSmells = buildBackendSmells();
      const selectedIds = allSmells
        .filter((s) => selection.has(s.location.file))
        .map((s) => s.id);
      const selectedFiles = Array.from(selection);

      const res = await api.post(`/workflows/${workflowId}/select-smells`, {
        selected_ids: selectedIds,
        selected_files: selectedFiles,
        feedback: { reason: "Selected in DIWO frontend" },
      });
      applyPlanResponse(res);
      setWorkflow((prev) => ({
        ...(prev || {}),
        updated_report: res.updated_report || prev?.updated_report,
        planning_input: res.planning_input || prev?.planning_input,
        smell_selection_summary: {
          total_smells: (res.updated_report?.summary?.total_code_smells) || 0,
          selected_count: res.selected_count || 0,
          excluded_count: res.excluded_count || 0,
        },
      }));
      setPhase(1);
    } catch (e) {
      // FIX [F3]
      addLog(`Smell selection failed: ${e.message}`, "danger");
    } finally {
      setBackendBusy(false);
    }
  };

  // ── Stage 1 → 2: Plan approval ────────────────────────────────────────────
  const handlePlanDecisionChange = async ({ decisions, preferences }) => {
    if (!workflowId || !planData || backendBusy) return;

    try {
      setBackendBusy(true);
      const res = await api.post(`/workflows/${workflowId}/plan-preference-update`, {
        decisions,
        preferences,
      });

      const updatedPlan = res.updated_planning_report || null;
      if (updatedPlan) {
        setPlanData(updatedPlan);
        addLog("Updated plan regenerated from developer preferences.", "info");
      }
    } catch (e) {
      addLog(`Plan preference update failed: ${e.message}`, "warn");
    } finally {
      setBackendBusy(false);
    }
  };

  const handlePlanApproved = async ({ decisions, opinion, plan }) => {
    if (backendBusy) return; // FIX [F2]

    // The page hands back the plan it rendered (RDP-generated or workflow copy),
    // so the approved steps always match what the developer reviewed.
    const activePlan = plan || planData;

    const approved = Object.values(decisions).filter((d) => d === "approve").length;
    const rejected = Object.values(decisions).filter((d) => d === "reject").length;
    addLog(`${approved} steps approved, ${rejected} rejected — forwarding to Transformation Agent`, "success");
    if (opinion) addLog(`Developer note: "${opinion.slice(0, 80)}"`, "info");

    if (!workflowId || !activePlan) {
      addLog("No backend session — cannot submit plan. Check backend connection.", "danger");
      return;
    }

    try {
      setBackendBusy(true);
      const approvedSteps = (activePlan.steps || []).filter(
        (s) => decisions[s.step_id] === "approve"
      );

      if (approvedSteps.length === 0) {
        addLog("At least one step must be approved to continue.", "warn");
        return;
      }

      // The backend derives the approved-only plan from the decisions and
      // persists it, so the report Stage 3 posts to /sctva/execute is the same
      // one the audit trail records. The local filter below is only the
      // fallback for an offline backend.
      let approvedReport = { ...activePlan, steps: approvedSteps };

      if (approvedSteps.length < (activePlan.steps || []).length) {
        const modRes = await api.post(`/workflows/${workflowId}/plan-decision`, {
          decision: "modify",
          decisions,
          feedback: { reason: opinion || "Developer adjusted plan" },
        });
        if (modRes.plan) {
          approvedReport = modRes.plan;
          setPlanData(modRes.plan);
        }
      }

      // Then approve — carries the decisions too, so an all-approved plan is
      // still persisted with its approval block.
      const approveRes = await api.post(`/workflows/${workflowId}/plan-decision`, {
        decision: "approve",
        decisions,
        feedback: { reason: opinion || "Approved in DIWO frontend", rating: 5 },
      });
      if (approveRes.approved_plan) approvedReport = approveRes.approved_plan;

      const forwarded = (approvedReport.steps || []).length;
      addLog(
        `Forwarding the approved plan (${forwarded} step(s), ` +
        `${(approvedReport.approval?.rejected_step_ids || []).length} rejected) ` +
        "to the Safe Transformation Agent.",
        "success"
      );
      setApprovedPlan(approvedReport);

      // FIX [F4]: Store real backend transformation data
      const td = {
        refactored_code: approveRes.refactored_code || "",
        diff_rows:       approveRes.diff_rows || [],
        files:           approveRes.files || [],
      };
      setTransformationData(td);
      setMetricsAfterApi(approveRes.metrics_after || null);
      addLog("Transformation completed by backend. Showing results.", "success");
      // store plan approval summary for reporting
      setWorkflow((prev) => ({
        ...(prev || {}),
        plan_approval_summary: {
          total_steps: (activePlan?.steps || []).length || 0,
          approved_count: approved,
          rejected_count: rejected,
        },
        // also store transformation files temporarily
        files: approveRes.files || td.files || [],
      }));

      setPhase(2);
    } catch (e) {
      addLog(`Plan decision failed: ${e.message}`, "danger"); // FIX [F3]
    } finally {
      setBackendBusy(false);
    }
  };

  // ── Stage 2 → 3: Transformation complete ─────────────────────────────────
  /**
   * FIX [F4]: Called by TransformationApprovalPage with the result it is
   * showing — the Safe Transformation Agent's own output when SCTVA ran, the
   * DIWO backend's simulated result when the developer fell back to it.
   */
  const handleTransformComplete = (payload = {}) => {
    const td = payload.refactored_code || (payload.files || []).length
      ? payload
      : (transformationData || {});
    const sctva = td.sctva || null;

    if (sctva) {
      const confidence = typeof sctva.confidence_score === "number"
        ? `${(sctva.confidence_score * 100).toFixed(1)}%`
        : "not applicable";
      addLog(
        `Safe Code Transformation Agent completed (${sctva.agent_url}): ` +
        `${sctva.file_summary?.applied ?? 0}/${sctva.file_summary?.total ?? 0} file(s) changed, ` +
        `${sctva.total_replacements ?? 0} replacement(s), confidence ${confidence}` +
        (sctva.rollback_occurred ? " — rollback performed" : ""),
        sctva.rollback_occurred ? "warn" : "success"
      );
    } else {
      addLog("Transformation stage completed with the DIWO backend's simulated result.", "warn");
    }

    const acceptedFiles = td.accepted_files || [];
    const rejectedFiles = td.rejected_files || [];
    if (acceptedFiles.length || rejectedFiles.length) {
      addLog(
        `Developer reviewed the transformed files: ${acceptedFiles.length} accepted, ` +
        `${rejectedFiles.length} rejected.`,
        rejectedFiles.length ? "warn" : "success"
      );
      rejectedFiles.forEach((path) => addLog(`Rejected refactoring of ${path}`, "warn"));
    }

    setTransformationData(td);

    const before = metricsBeforeApi || {
      cyclomatic_complexity: 35, code_duplication_pct: 18,
      maintainability_index: 65, total_smells: CUQA_DATA.summary.total_code_smells,
      smell_breakdown: CUQA_DATA.summary.smell_severity,
    };
    const after = metricsAfterApi || {
      cyclomatic_complexity: 24, code_duplication_pct: 9,
      maintainability_index: 82,
      total_smells: Math.max(0, CUQA_DATA.summary.total_code_smells - 32),
      smell_breakdown: {
        high:   Math.max(0, (CUQA_DATA.summary.smell_severity.high || 0) - 6),
        medium: Math.max(0, (CUQA_DATA.summary.smell_severity.medium || 0) - 2),
        low:    Math.max(0, (CUQA_DATA.summary.smell_severity.low || 0) - 24),
      },
      improvements: { complexity_reduced_by: 11, duplication_reduced_by: 9, maintainability_gained: 17 },
    };

    setWorkflow((prev) => ({
      ...(prev || {}),
      metrics_before:  before,
      metrics_after:   after,
      refactored_code: td.refactored_code || "",
      diff_rows:       td.diff_rows || [],
      files:           td.files || [],
      sctva,
      // Stage 3's per-file verdict, kept apart from the Results stage's own
      // accept list so the two decisions stay distinguishable in the audit.
      transformation_accepted_files: acceptedFiles,
      transformation_rejected_files: rejectedFiles,
    }));
    setPhase(3);
  };

  // ── Stage 3: Accept → go to comparison ───────────────────────────────────
  const handleAccept = async (payload = {}) => {
    const acceptedEntries = Array.isArray(payload.acceptedFiles) ? payload.acceptedFiles : [];
    const written_paths = acceptedEntries.map((f) => f.path || f.relative_path || f.file || f);
    // Files the developer rejected in Stage 3 were reverted to their original
    // source before being written, so report them separately from files that
    // were simply left out of this commit.
    const reverted_paths = Array.isArray(payload.revertedFiles)
      ? payload.revertedFiles
      : (workflow?.transformation_rejected_files || []);
    const accepted_paths = written_paths.filter((p) => !reverted_paths.includes(p));
    const allFiles = (workflow?.files && workflow.files.length > 0) ? workflow.files : (transformationData?.files || []);
    const all_paths = allFiles.map((f) => f.path || f.relative_path || f.file || f);
    const rejected_paths = all_paths.filter((p) => !accepted_paths.includes(p));

    // The final source of every file, so the backend can build the downloadable
    // archive. A rejected file contributes its original text; a rejected file
    // whose original never arrived is left out entirely rather than shipping
    // the change the developer declined.
    const archive_files = allFiles
      .filter((f) => !(f.decision === "reject" && !(f.before || "")))
      .map((f) => {
        const reverted = f.decision === "reject" && Boolean(f.before);
        return {
          path: f.path || f.relative_path || f.file || "",
          content: reverted ? f.before : (f.after || f.refactored_code || ""),
          state: reverted ? "reverted_to_original" : "refactored",
        };
      })
      .filter((f) => f.path && f.content);

    addLog(
      `Developer committed ${written_paths.length} file(s): ${accepted_paths.length} refactored, ` +
      `${reverted_paths.length} reverted to original.`,
      "info"
    );

    let archive = null;
    if (workflowId) {
      try {
        const res = await api.post(`/workflows/${workflowId}/transformation-decision`, {
          decision: "accept",
          accepted_files: accepted_paths,
          rejected_files: reverted_paths,
          written_files: written_paths,
          files: archive_files,
          feedback: { reason: "Accepted from frontend", rating: 5 },
        });
        archive = res.archive || null;
        if (archive) {
          addLog(
            `Refactored archive ready: ${archive.file_count} file(s), ` +
            `${Math.round(archive.bytes / 1024)} KB.`,
            "success"
          );
        } else if (res.archive_error) {
          addLog(`Archive could not be built: ${res.archive_error}`, "warn");
        }
      } catch (e) {
        addLog(`Backend accept call failed: ${e.message}`, "warn");
      }
    }

    setWorkflow((prev) => ({
      ...(prev || {}),
      accepted_files: accepted_paths,
      rejected_files: rejected_paths,
      archive,
    }));

    setPhase(4);
  };

  // ── Stage 3: Rollback ─────────────────────────────────────────────────────
  /**
   * FIX [F5]: Await the backend rollback before changing phase so the DB is
   * consistent before the user sees the plan-review screen again.
   */
  const handleRollback = async () => {
    addLog("Developer requested rollback. Reverting to pre-transformation state.", "danger");
    if (workflowId) {
      try {
        await api.post(`/workflows/${workflowId}/transformation-decision`, {
          decision: "rollback",
          feedback: { reason: "Rollback requested from frontend" },
        });
        addLog("Rollback recorded in backend.", "info");
      } catch (e) {
        addLog(`Backend rollback failed: ${e.message}`, "warn");
      }
    }
    // Drop the approved steps so the next approval re-runs SCTVA from scratch.
    setApprovedPlan(null);
    setTransformationData(null);
    setPhase(1);
  };

  // ── Restart ───────────────────────────────────────────────────────────────
  const handleRestart = () => {
    addLog("New refactoring session initiated.", "info");
    setApprovedPlan(null);
    setTransformationData(null);
    setPhase(0);
  };

  // ─── Render ───────────────────────────────────────────────────────────────
  return (
    <div style={{ background: C.bg, minHeight: "100vh", color: C.text, fontFamily: "'DM Sans', 'Segoe UI', sans-serif" }}>
      {/* Header */}
      <div style={{ background: C.panel, borderBottom: `1px solid ${C.border}`, padding: "0 32px", display: "flex", alignItems: "center", justifyContent: "space-between", height: 56 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{ width: 28, height: 28, borderRadius: 6, background: C.gradient, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 900, color: "#000" }}>D</div>
          <span style={{ fontSize: 14, fontWeight: 700, letterSpacing: 0.3 }}>DIWO Agent</span>
          <span style={{ fontSize: 11, color: C.textMuted, padding: "2px 8px", background: C.bg, borderRadius: 4, border: `1px solid ${C.border}` }}>Developer Interaction & Workflow Orchestration</span>
          {/* FIX [F2]: Busy indicator */}
          {backendBusy && (
            <span style={{ fontSize: 11, color: C.warn, padding: "2px 8px", background: `${C.warn}15`, borderRadius: 4, border: `1px solid ${C.warn}40` }}>
              ⏳ Contacting backend…
            </span>
          )}
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: workflowId ? C.accent : C.warn, boxShadow: `0 0 8px ${workflowId ? C.accent : C.warn}` }} />
          <span style={{ fontSize: 11, color: C.textMuted }}>
            {workflowId ? `wf: ${workflowId}` : "offline"} · R26-SE-008 · IT22277886
          </span>
        </div>
      </div>

      <div style={{ display: "flex", height: "calc(100vh - 56px)" }}>
        <div style={{ flex: 1, overflow: "auto", padding: "28px 32px" }}>
          <StepBar current={phase} />

          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: 20, fontWeight: 800, color: C.text, marginBottom: 4 }}>{PHASE_TITLES[phase]}</div>
            <div style={{ fontSize: 13, color: C.textMuted }}>{PHASE_DESCRIPTIONS[phase]}</div>
          </div>

          {phase === 0 && (
            <CodeSmellApprovalPage
              workflowId={workflowId}
              onProceed={handleSmellsSelected}
              reportData={workflow?.updated_report || cuqaReport || null}
              onReportLoaded={handleCuqaReportLoaded}
            />
          )}
          {phase === 1 && (
            <RefactoringPlanApprovalPage
              planData={planData}
              planMeta={planMeta}
              loading={backendBusy && !planData}
              onDecisionChange={handlePlanDecisionChange}
              onApprove={handlePlanApproved}
              onFallback={() => { addLog("Developer fell back to Smell Review.", "warn"); setPhase(0); }}
            />
          )}
          {phase === 2 && (
            <TransformationApprovalPage
              plan={approvedPlan || planData}
              language={workflowLanguage}
              transformationData={transformationData}
              onComplete={handleTransformComplete}
            />
          )}
          {phase === 3 && (
            <ResultsApprovalPage
              onRestart={handleRestart}
              onRollback={handleRollback}
              onAccept={handleAccept}
              refactoredCode={workflow?.refactored_code}
              diffRows={workflow?.diff_rows}
              files={workflow?.files}
              sctva={workflow?.sctva}
            />
          )}
          {phase === 4 && (
            <ComparisonView
                workflow={workflow}
                workflowId={workflowId}
                language={workflowLanguage}
              auditLogs={auditLog}
              onComplete={async (notes) => {
                if (workflowId) {
                  try {
                    await api.post(`/workflows/${workflowId}/complete`, { notes: notes || "" });
                  } catch (e) {
                    addLog(`Complete workflow failed: ${e.message}`, "warn");
                  }
                }
                addLog("Comparison completed. Session closed.", "success");
                setPhase(0);
              }}
              onLoadLogs={async () => {
                if (!workflowId) return;
                try {
                  const logs = await api.get(`/workflows/${workflowId}/audit-logs`);
                  // Merge backend logs with local logs, deduplicated by id
                  setAuditLog((prev) => {
                    const ids = new Set(prev.map((l) => l.id));
                    const merged = [...prev];
                    logs.forEach((l) => {
                      const key = String(l.id);
                      if (!ids.has(key)) {
                        ids.add(key);
                        merged.push({
                          id: key,
                          time: new Date(l.timestamp).toLocaleTimeString(),
                          event: `[${l.stage}] ${l.action} (${l.actor})`,
                          type: "info",
                        });
                      }
                    });
                    return merged;
                  });
                  addLog("Audit logs synced from backend.", "success");
                } catch (e) {
                  addLog(`Audit sync failed: ${e.message}`, "warn");
                }
              }}
              loading={false}
            />
          )}
        </div>

        <AuditSidebar phase={phase} auditLog={auditLog} />
      </div>
    </div>
  );
}
