import { useState } from "react";
import AuditSidebar from "./AuditSidebar";
import CodeSmellApprovalPage from "./CodeSmellApprovalPage";
import RefactoringPlanApprovalPage from "./RefactoringPlanApprovalPage";
import ResultsApprovalPage from "./ResultsApprovalPage";
import TransformationApprovalPage from "./TransformationApprovalPage";
import { C, StepBar } from "./diwoTheme.jsx";

const PHASE_TITLES = [
  "Code Smell Review",
  "Refactoring Plan Review",
  "Safe Code Transformation",
  "Refactoring Results",
];

const PHASE_DESCRIPTIONS = [
  "Analyze detected code smells from Code Understanding Agent and select smells to forward to the Refactoring Planning Agent.",
  "Review, approve, reject, or reprioritize the refactoring plan generated by the Refactoring Planning Agent.",
  "Safe Code Transformation & Validation Agent is applying approved refactoring actions with full behavioral validation.",
  "Review the refactored output, validation report, and confidence metrics. Accept, rollback, or start a new session.",
];

export default function DIWOAgentPage() {
  const [phase, setPhase] = useState(0);
  const [auditLog, setAuditLog] = useState([
    { time: new Date().toLocaleTimeString(), event: "Session initialized", type: "info" }
  ]);

  const addLog = (event, type = "info") => {
    setAuditLog(prev => [...prev, { time: new Date().toLocaleTimeString(), event, type }]);
  };

  const handleSmellsSelected = (selected) => {
    addLog(`${selected.size} files forwarded to Refactoring Planning Agent`, "success");
    setPhase(1);
  };

  const handlePlanApproved = ({ decisions, opinion }) => {
    const approved = Object.values(decisions).filter(d => d === "approve").length;
    const rejected = Object.values(decisions).filter(d => d === "reject").length;
    addLog(`Plan approved: ${approved} steps approved, ${rejected} rejected. Forwarding to Transformation Agent.`, "success");
    if (opinion) addLog(`Developer note recorded: "${opinion.slice(0, 60)}..."`, "info");
    setPhase(2);
  };

  const handleTransformComplete = () => {
    addLog("Safe Code Transformation Agent completed. Confidence: 100%", "success");
    setPhase(3);
  };

  const handleRollback = () => {
    addLog("Developer requested rollback. Reverting to pre-transformation state.", "danger");
    setPhase(1);
  };

  const handleRestart = () => {
    addLog("New refactoring session initiated.", "info");
    setPhase(0);
  };

  return (
    <div style={{ background: C.bg, minHeight: "100vh", color: C.text, fontFamily: "'DM Sans', 'Segoe UI', sans-serif", padding: "0" }}>
      <div style={{ background: C.panel, borderBottom: `1px solid ${C.border}`, padding: "0 32px", display: "flex", alignItems: "center", justifyContent: "space-between", height: 56 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{ width: 28, height: 28, borderRadius: 6, background: C.gradient, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 900, color: "#000" }}>D</div>
          <span style={{ fontSize: 14, fontWeight: 700, letterSpacing: 0.3 }}>DIWO Agent</span>
          <span style={{ fontSize: 11, color: C.textMuted, padding: "2px 8px", background: C.bg, borderRadius: 4, border: `1px solid ${C.border}` }}>Developer Interaction & Workflow Orchestration</span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <div style={{ width: 8, height: 8, borderRadius: "50%", background: C.accent, boxShadow: `0 0 8px ${C.accent}` }} />
          <span style={{ fontSize: 11, color: C.textMuted }}>R26-SE-008 · IT22277886</span>
        </div>
      </div>

      <div style={{ display: "flex", height: "calc(100vh - 56px)" }}>
        <div style={{ flex: 1, overflow: "auto", padding: "28px 32px" }}>
          <StepBar current={phase} />

          <div style={{ marginBottom: 20 }}>
            <div style={{ fontSize: 20, fontWeight: 800, color: C.text, marginBottom: 4 }}>{PHASE_TITLES[phase]}</div>
            <div style={{ fontSize: 13, color: C.textMuted }}>{PHASE_DESCRIPTIONS[phase]}</div>
          </div>

          {phase === 0 && <CodeSmellApprovalPage onProceed={handleSmellsSelected} />}
          {phase === 1 && <RefactoringPlanApprovalPage onApprove={handlePlanApproved} onFallback={() => { addLog("Developer fell back to Smell Review phase.", "warn"); setPhase(0); }} />}
          {phase === 2 && <TransformationApprovalPage onComplete={handleTransformComplete} />}
          {phase === 3 && <ResultsApprovalPage onRestart={handleRestart} onRollback={handleRollback} />}
        </div>

        <AuditSidebar phase={phase} auditLog={auditLog} />
      </div>
    </div>
  );
}
