/**
 * Reports.jsx — Quality & Audit Reports Page
 * Displays generated quality reports from CUQA analysis runs, allowing preview,
 * filtering, and export (JSON/CSV).
 */

import { useState, useEffect } from 'react';

const API = 'http://localhost:8080';
const HISTORY_KEY     = 'cuqa_analysis_history';
const RDP_HISTORY_KEY = 'rdp_plan_history';

function loadHistory() {
  try { return JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]'); }
  catch { return []; }
}

function loadRdpHistory() {
  try { return JSON.parse(localStorage.getItem(RDP_HISTORY_KEY) || '[]'); }
  catch { return []; }
}

function fmtDate(iso) {
  if (!iso) return 'N/A';
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
  });
}

function scoreColor(s) {
  if (s >= 80) return '#22c55e';
  if (s >= 60) return '#f59e0b';
  return '#ef4444';
}

export default function Reports() {
  const [history,       setHistory]       = useState([]);
  const [rdpHistory,    setRdpHistory]    = useState([]);
  const [search,        setSearch]        = useState('');
  const [langFilter,    setLangFilter]    = useState('All');
  const [agentFilter,   setAgentFilter]   = useState('All');   // 'All' | 'CUQA' | 'RDP'
  const [selectedReport,  setSelectedReport]  = useState(null);
  const [selectedRdpPlan, setSelectedRdpPlan] = useState(null);
  const [liveReport,    setLiveReport]    = useState(null);
  const [loadingLive,   setLoadingLive]   = useState(false);

  useEffect(() => {
    setHistory(loadHistory());
    setRdpHistory(loadRdpHistory());
    fetchLiveReport();
  }, []);

  async function fetchLiveReport() {
    try {
      setLoadingLive(true);
      const res = await fetch(`${API}/api/quality-report`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      if (res.ok) {
        const data = await res.json();
        setLiveReport(data.report);
      }
    } catch {
      // Backend off or no workspace
    } finally {
      setLoadingLive(false);
    }
  }

  function exportRdpPlanJSON(planItem) {
    const dataStr = JSON.stringify(planItem.plan || planItem, null, 2);
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `rdp_plan_${planItem.plan_id || planItem.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const filteredHistory = history.filter(item => {
    const matchesSearch = item.name?.toLowerCase().includes(search.toLowerCase());
    const matchesLang   = langFilter === 'All' || item.language?.toLowerCase() === langFilter.toLowerCase();
    const matchesAgent  = agentFilter === 'All' || agentFilter === 'CUQA';
    return matchesSearch && matchesLang && matchesAgent;
  });

  const filteredRdpHistory = rdpHistory.filter(item => {
    const matchesSearch = item.target?.toLowerCase().includes(search.toLowerCase()) ||
                          item.source_file?.toLowerCase().includes(search.toLowerCase());
    const matchesAgent  = agentFilter === 'All' || agentFilter === 'RDP';
    return matchesSearch && matchesAgent;
  });

  const totalPlans = rdpHistory.length;
  const avgSteps   = rdpHistory.length
    ? Math.round(rdpHistory.reduce((a, b) => a + (b.step_count || 0), 0) / rdpHistory.length)
    : 0;

  function exportReportJSON(reportItem) {
    const dataStr = JSON.stringify(reportItem, null, 2);
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `report_${reportItem.name || 'analysis'}.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function exportAllCSV() {
    if (!history.length) return;
    const header = 'Repository,Language,Date,Files,Score,Threshold,Mode';
    const rows = history.map(r =>
      `"${r.name}","${r.language}","${fmtDate(r.date)}","${r.files_found}","${r.score}%","${r.threshold}%","${r.mode}"`
    );
    const csv = [header, ...rows].join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'refactoriq_all_reports.csv';
    a.click();
    URL.revokeObjectURL(url);
  }

  const avgScore = history.length
    ? Math.round(history.reduce((a, b) => a + (b.score || 0), 0) / history.length)
    : 0;

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header">
        <div className="page-header-left">
          <div className="page-header-icon">📋</div>
          <div>
            <div className="page-title">Reports &amp; Quality Audits</div>
            <div className="page-subtitle">
              Exportable AST quality reports, smell assessments, and execution logs generated by <strong style={{ color: 'var(--accent)' }}>RefactorIQ</strong>.
            </div>
          </div>
        </div>
        <div className="page-header-actions">
          <button className="btn btn-outline" onClick={exportAllCSV} disabled={!history.length}>
            ↓ Export CSV Summary
          </button>
        </div>
      </div>

      {/* Top Metrics Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 14 }}>
        <div className="card card-body" style={{ padding: 18 }}>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>CUQA Reports</div>
          <div style={{ fontSize: 26, fontWeight: 800, color: 'var(--accent)', marginTop: 4 }}>{history.length}</div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 4 }}>Quality analyses</div>
        </div>
        <div className="card card-body" style={{ padding: 18 }}>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>RDP Plans</div>
          <div style={{ fontSize: 26, fontWeight: 800, color: '#a78bfa', marginTop: 4 }}>{totalPlans}</div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 4 }}>Refactoring plans</div>
        </div>
        <div className="card card-body" style={{ padding: 18 }}>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>Avg Code Score</div>
          <div style={{ fontSize: 26, fontWeight: 800, color: scoreColor(avgScore), marginTop: 4 }}>{avgScore > 0 ? `${avgScore}%` : '—'}</div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 4 }}>Across CUQA runs</div>
        </div>
        <div className="card card-body" style={{ padding: 18 }}>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>Avg Steps / Plan</div>
          <div style={{ fontSize: 26, fontWeight: 800, color: '#22c55e', marginTop: 4 }}>{avgSteps || '—'}</div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 4 }}>Refactoring steps</div>
        </div>
        <div className="card card-body" style={{ padding: 18 }}>
          <div style={{ fontSize: 10, color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>Export Formats</div>
          <div style={{ fontSize: 20, fontWeight: 700, color: 'var(--text-primary)', marginTop: 8 }}>JSON · CSV</div>
          <div style={{ fontSize: 11, color: 'var(--text-secondary)', marginTop: 4 }}>Automated schema</div>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="card" style={{ padding: '12px 16px', display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
        <div style={{ flex: 1, minWidth: 220 }}>
          <input
            className="input"
            placeholder="Search by repository or target name..."
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Agent:</span>
          {['All', 'CUQA', 'RDP'].map(a => (
            <button key={a} className={`btn btn-sm ${agentFilter === a ? 'btn-primary' : 'btn-ghost'}`}
              onClick={() => setAgentFilter(a)}>{a}</button>
          ))}
        </div>
        <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
          <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>Language:</span>
          {['All', 'Java', 'Python', 'C'].map(l => (
            <button key={l} className={`btn btn-sm ${langFilter === l ? 'btn-primary' : 'btn-ghost'}`}
              onClick={() => setLangFilter(l)}>{l}</button>
          ))}
        </div>
      </div>

      {/* CUQA Reports Table */}
      {(agentFilter === 'All' || agentFilter === 'CUQA') && (
      <div className="card">
        <div className="card-header">
          <span className="card-title">🔍 CUQA Quality Reports ({filteredHistory.length})</span>
        </div>
        {filteredHistory.length === 0 ? (
          <div className="empty-state" style={{ padding: 40 }}>
            <span className="empty-icon">📋</span>
            <p>No CUQA reports yet. Run a code analysis in <strong>Repository Input</strong> first.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Repository Name</th>
                  <th>Source</th>
                  <th>Language</th>
                  <th>Mode</th>
                  <th>Timestamp</th>
                  <th>Files</th>
                  <th>Score</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredHistory.map(r => (
                  <tr key={r.id}>
                    <td><span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{r.name}</span></td>
                    <td><span className="badge badge-accent" style={{ fontSize: 10 }}>{r.source === 'github' ? '🔗 GitHub' : '📁 ZIP'}</span></td>
                    <td><span className={`badge badge-${(r.language || '').toLowerCase()}`}>{r.language}</span></td>
                    <td style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{r.mode || 'Comprehensive'}</td>
                    <td style={{ fontSize: 11, color: 'var(--text-muted)' }}>{fmtDate(r.date)}</td>
                    <td style={{ fontSize: 11 }}>{r.files_found} files</td>
                    <td><span style={{ fontWeight: 700, color: r.color }}>{r.score}%</span></td>
                    <td>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button className="btn btn-ghost btn-sm" onClick={() => setSelectedReport(r)}>👁️ View</button>
                        <button className="btn btn-outline btn-sm" onClick={() => exportReportJSON(r)}>↓ JSON</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
      )}

      {/* RDP Plan History Table */}
      {(agentFilter === 'All' || agentFilter === 'RDP') && (
      <div className="card">
        <div className="card-header">
          <span className="card-title">🧠 RDP Refactoring Plans ({filteredRdpHistory.length})</span>
        </div>
        {filteredRdpHistory.length === 0 ? (
          <div className="empty-state" style={{ padding: 40 }}>
            <span className="empty-icon">📋</span>
            <p>No RDP plans yet. Upload a CUQA quality report in the <strong>RDP Agent</strong> tab to generate a plan.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Plan ID</th>
                  <th>Target</th>
                  <th>Source File</th>
                  <th>Timestamp</th>
                  <th>Steps</th>
                  <th>Top Refactorings</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredRdpHistory.map(r => (
                  <tr key={r.id}>
                    <td><span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#a78bfa' }}>{r.plan_id}</span></td>
                    <td><span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{r.target}</span></td>
                    <td style={{ fontSize: 11, color: 'var(--text-secondary)' }}>{r.source_file}</td>
                    <td style={{ fontSize: 11, color: 'var(--text-muted)' }}>{fmtDate(r.date)}</td>
                    <td>
                      <span style={{ fontWeight: 700, color: '#22c55e' }}>{r.step_count}</span>
                      <span style={{ fontSize: 10, color: 'var(--text-muted)', marginLeft: 4 }}>steps</span>
                    </td>
                    <td style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
                      {(r.refactorings || []).join(', ') || '—'}
                    </td>
                    <td>
                      <div style={{ display: 'flex', gap: 6 }}>
                        <button className="btn btn-ghost btn-sm" onClick={() => setSelectedRdpPlan(r)}>👁️ View</button>
                        <button className="btn btn-outline btn-sm" onClick={() => exportRdpPlanJSON(r)}>↓ JSON</button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
      )}

      {/* Selected Report Modal / View */}
      {selectedReport && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          background: 'rgba(0,0,0,0.7)', zIndex: 1000, display: 'flex',
          alignItems: 'center', justifyContent: 'center', padding: 20
        }}>
          <div className="card" style={{ width: '100%', maxWidth: 640, maxHeight: '80vh', overflowY: 'auto', padding: 24 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, borderBottom: '1px solid var(--border)', paddingBottom: 12 }}>
              <h3 style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)' }}>
                📊 Quality Report: {selectedReport.name}
              </h3>
              <button className="btn btn-ghost btn-sm" onClick={() => setSelectedReport(null)}>✕ Close</button>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 16 }}>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>LANGUAGE CONTEXT</div>
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{selectedReport.language}</div>
              </div>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>QUALITY SCORE</div>
                <div style={{ fontSize: 13, fontWeight: 700, color: selectedReport.color }}>{selectedReport.score}%</div>
              </div>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>ANALYSIS THRESHOLD</div>
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{selectedReport.threshold}%</div>
              </div>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>FILES DETECTED</div>
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-primary)' }}>{selectedReport.files_found}</div>
              </div>
            </div>

            <div style={{ marginBottom: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', marginBottom: 6 }}>FILTERS APPLIED AT RUNTIME</div>
              <div style={{ display: 'flex', gap: 8 }}>
                <span className="badge badge-accent">Critical Issues: {selectedReport.filters?.critical ? 'ENABLED' : 'DISABLED'}</span>
                <span className="badge badge-accent">Naming Violations: {selectedReport.filters?.naming ? 'ENABLED' : 'DISABLED'}</span>
              </div>
            </div>

            <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
              <button className="btn btn-outline" onClick={() => exportReportJSON(selectedReport)}>
                ↓ Download Full Report JSON
              </button>
            </div>
          </div>
        </div>
      )}
      {/* RDP Plan Modal */}
      {selectedRdpPlan && (
        <div style={{
          position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
          background: 'rgba(0,0,0,0.7)', zIndex: 1000, display: 'flex',
          alignItems: 'center', justifyContent: 'center', padding: 20
        }}>
          <div className="card" style={{ width: '100%', maxWidth: 680, maxHeight: '82vh', overflowY: 'auto', padding: 24 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, borderBottom: '1px solid var(--border)', paddingBottom: 12 }}>
              <h3 style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)' }}>
                🧠 Refactoring Plan: {selectedRdpPlan.target}
              </h3>
              <button className="btn btn-ghost btn-sm" onClick={() => setSelectedRdpPlan(null)}>✕ Close</button>
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12, marginBottom: 16 }}>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>PLAN ID</div>
                <div style={{ fontSize: 12, fontWeight: 600, color: '#a78bfa', fontFamily: 'var(--font-mono)' }}>{selectedRdpPlan.plan_id}</div>
              </div>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>STEPS</div>
                <div style={{ fontSize: 20, fontWeight: 800, color: '#22c55e' }}>{selectedRdpPlan.step_count}</div>
              </div>
              <div style={{ background: 'var(--bg-elevated)', padding: 12, borderRadius: 'var(--r-sm)' }}>
                <div style={{ fontSize: 10, color: 'var(--text-muted)' }}>SOURCE FILE</div>
                <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)' }}>{selectedRdpPlan.source_file}</div>
              </div>
            </div>
            {selectedRdpPlan.summary && (
              <p style={{ fontSize: 12, color: 'var(--text-secondary)', marginBottom: 16, lineHeight: 1.6 }}>{selectedRdpPlan.summary}</p>
            )}
            <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
              <button className="btn btn-outline" onClick={() => exportRdpPlanJSON(selectedRdpPlan)}>↓ Download Plan JSON</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
